services:
  db:
    image: postgres:latest
    env_file:
      - .env-non-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    depends_on:
      - db
    ports:
      - "9000:8000"
    command: ["sh", "-c", "until pg_isready -h db -U ${DB_USER}; do sleep 1; done && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"]

volumes:
  postgres_data: